---
# =============================================================================
# Local (Mac) Configuration
# =============================================================================

# Какой клиент использовать из vault_client_uuids
vpn_client_name: ione-MacBook
